{
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "An issue was discovered in llama_index before 0.10.38. download/integration.py includes an exec call for import {cls_name}."
    },
    {
      "lang": "es",
      "value": "Se descubri√≥ un problema en llama_index antes del 0.10.38. download/integration.py incluye una llamada ejecutiva para importar {cls_name}."
    }
  ],
  "id": "CVE-2024-45201",
  "lastModified": "2024-11-25T19:15:10.473",
  "metrics": {
    "cvssMetricV31": [
      {
        "cvssData": {
          "attackComplexity": "LOW",
          "attackVector": "NETWORK",
          "availabilityImpact": "HIGH",
          "baseScore": 8.8,
          "baseSeverity": "HIGH",
          "confidentialityImpact": "HIGH",
          "integrityImpact": "HIGH",
          "privilegesRequired": "LOW",
          "scope": "UNCHANGED",
          "userInteraction": "NONE",
          "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
          "version": "3.1"
        },
        "exploitabilityScore": 2.8,
        "impactScore": 5.9,
        "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
        "type": "Secondary"
      }
    ]
  },
  "published": "2024-08-22T20:15:10.063",
  "references": [
    {
      "source": "cve@mitre.org",
      "url": "https://github.com/run-llama/llama_index/compare/v0.10.37...v0.10.38"
    },
    {
      "source": "cve@mitre.org",
      "url": "https://github.com/run-llama/llama_index/pull/13523"
    }
  ],
  "sourceIdentifier": "cve@mitre.org",
  "vulnStatus": "Awaiting Analysis",
  "weaknesses": [
    {
      "description": [
        {
          "lang": "en",
          "value": "CWE-94"
        }
      ],
      "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
      "type": "Secondary"
    }
  ]
}