{
  "cveTags": [],
  "descriptions": [
    {
      "lang": "en",
      "value": "Portainer before 2.20.2 improperly uses an encryption algorithm in the AesEncrypt function."
    },
    {
      "lang": "es",
      "value": "Portainer anterior a 2.20.2 utiliza incorrectamente un algoritmo de cifrado en la funci√≥n AesEncrypt."
    }
  ],
  "id": "CVE-2024-33662",
  "lastModified": "2024-12-04T17:15:12.523",
  "metrics": {
    "cvssMetricV31": [
      {
        "cvssData": {
          "attackComplexity": "HIGH",
          "attackVector": "NETWORK",
          "availabilityImpact": "HIGH",
          "baseScore": 7.5,
          "baseSeverity": "HIGH",
          "confidentialityImpact": "HIGH",
          "integrityImpact": "HIGH",
          "privilegesRequired": "LOW",
          "scope": "UNCHANGED",
          "userInteraction": "NONE",
          "vectorString": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H",
          "version": "3.1"
        },
        "exploitabilityScore": 1.6,
        "impactScore": 5.9,
        "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
        "type": "Secondary"
      }
    ]
  },
  "published": "2024-10-02T05:15:11.643",
  "references": [
    {
      "source": "cve@mitre.org",
      "url": "https://github.com/portainer/portainer/compare/2.20.1...2.20.2"
    },
    {
      "source": "cve@mitre.org",
      "url": "https://github.com/portainer/portainer/issues/11737"
    },
    {
      "source": "cve@mitre.org",
      "url": "https://www.portainer.io"
    }
  ],
  "sourceIdentifier": "cve@mitre.org",
  "vulnStatus": "Awaiting Analysis",
  "weaknesses": [
    {
      "description": [
        {
          "lang": "en",
          "value": "CWE-326"
        }
      ],
      "source": "134c704f-9b21-4f2e-91b3-4a467353bcc0",
      "type": "Secondary"
    }
  ]
}